### ISSUE TITLE
Turkish Characters Support

### ISSUE THREAD

**Issue by snndmnsz** [martpie/react-slugify#11]
Hi, 

Is it possible to add Turkish characters?

`turkishLetters = [
    "ç",
    "ğ",
    "ı",
    "ö",
    "ş",
    "ü",
    "Ç",
    "Ğ",
    "İ",
    "Ö",
    "Ş",
    "Ü",
  ];`

**Comment by martpie** [comment]
yes absolutely, will add those cases!

**Comment by martpie** [comment]
Should be fixed in `react-slugify@3.0.2` :)
