### ISSUE TITLE
Get error `Uncaught TypeError: (0 , import_react_slugify.default) is not a function error`

### ISSUE THREAD

**Issue by ccreusat** [martpie/react-slugify#15]
Hi,

I have this issue when using `react-slugify` in a custom hook and component in React. This is a library built with ViteJs.

In each file, this is how I use it : 

```
import slugify from "react-slugify";

const newSlug = `${hash({
    foo: `${resourceName}${uniqueId}`,
  })}-${slugify(resourceName)}`
```

It is used in a component created previously in my App without error.

`Uncaught TypeError: (0 , import_react_slugify.default) is not a function error`

Then I exported the component and the hook in the library.

Is there something wrong ?

**Comment by martpie** [comment]
What is your setup? Next? Webpack? Something else?

**Comment by ccreusat** [comment]
@martpie It's just a React application with ViteJS (React + TypeScript). Default configuration. Nothing fancy.

- I have the react components UI library which use `react-slugify` in a component like this : 

[file](https://github.com/opendigitaleducation/edifice-ui/blob/develop/packages/react/src/explorer/ResourceModal/ResourceModal.tsx)

```
import slugify from "react-slugify";

const newSlug = `${hash({
    foo: `${resourceName}${uniqueId}`,
  })}-${slugify(resourceName)}`
```

Then the component is imported in my React Application (lazy-load):

[file](https://github.com/opendigitaleducation/explorer/blob/6005ba1b32f2ee9c69acc1486f3373caf7224a60/frontend/src/features/Explorer/components/AppAction/AppAction.tsx)

```
const CreateModal = lazy(async () => {
  const module = await import("lib");
  return { default: module.ResourceModal };
});
```

and

```
<CreateModal
    mode="create"
    actions={actions}
    currentFolder={currentFolder}
    createResource={createResource}
    isOpen={isCreateResourceOpen}
    onSuccess={toggle}
    onCancel={toggle}
  />
```

The component is lazy-load + Suspense, but even without, I have the error.

If I duplicate the component directly in the app and use it .. no error ^^
