### ISSUE TITLE
End with delimiter

### ISSUE THREAD

**Issue by miff** [martpie/react-slugify#4]
In some case like...
`A little slug of mine @` -> `a-little-slug-of-mine-`
`A little slug of mine - Slug` -> `a-little-slug-of-mine---slug`

I added something like this: 
```
...
.replace(/\-\-+/g, '-') 
.replace(/\-+$/g, '')
```
to replace multiple -, and to remove - at the end 

btw, great package.

**Comment by martpie** [comment]
Hello! Sorry I just saw your comment now.

Thanks for the report, good catch, I'll look into it
