### ISSUE TITLE
Triplet Delimiter

### ISSUE THREAD

**Issue by Wilkrew** [martpie/react-slugify#7]
I've had this issue we're i get triplet delimiters. See simplified example below.

**Currently**
"Hello - World" ➜ "hello---world"

**Wanted Result**
"Hello - World" ➜ "hello-world"

I've resolved it by sadly replacing react-slugify for the time being with the following function:

export const slugifyer = (text) => {
  const mapObj = {
    å: "a",
    ä: "a",
    ö: "o",
    é: "e",
    ü: "u",
    ç: "c",
    è: "e",
    ê: "e",
    ë: "e",
    í: "i",
    ì: "i",
    î: "i",
    ï: "i",
    ñ: "n",
    ø: "o",
    ó: "o",
    ò: "o",
    ô: "o",
    õ: "o",
    ú: "u",
    ù: "u",
    û: "u",
    ý: "y",
    ÿ: "y",
    æ: "ae",
    œ: "oe",
  };
  text = text
    .toLowerCase()
    .trim()
    .replace(
      /(?:å|ä|ö|é|ü|ç|è|ê|ë|í|ì|ï|ñ|ø|ó|ò|ô|õ|ú|ù|û|ý|ÿ|æ|œcatch)/gm,
      (matched) => mapObj[matched]
    );

  text = text.replace(/\s+|-{2,}|\//gm, "-").replace(/\s+|-{2,}|\//gm, "-");       // Line and the one below fixes issue

  text = text.replace(/[^a-z0-9\s-]+|^-+|-+$/gm, ``);

  return text;
};

**Comment by martpie** [comment]
Hoi, sorry, I just saw your message now.

I have to fix it indeed, I added failing tests in #5, but I was failing challenges making it work well. I'll try again!

**Comment by martpie** [comment]
Fixed in #5.

I have two edgecases to fix and then I'll release it!
